POST http://localhost:8080/categories
Content-Type: application/json

{
  "id": 1,
  "name": "Electronics"
}


###

GET http://localhost:8080/categories

###

GET http://localhost:8080/categories/1

###

PUT http://localhost:8080/categories/2
Content-Type: application/json

{
  "id": 1,
  "name": "Apparel"
}


###

DELETE http://localhost:8080/categories/1